version: "3"
services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  front:
    depends_on:
      - back
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000